openapi: 3.0.0
info:
  title: Sample API
  description: API with Basic Authentication
  version: 1.0.0
servers:
  - url: https://api.example.com/v1
components:
  securitySchemes:
    basicAuth:
      type: http
      scheme: basic
    apiKeyAuth:
      type: apiKey
      in: header
      name: X-API-Key
    oauth2Implicit:
      type: oauth2
      flows:
        implicit:
          authorizationUrl: https://example.com/oauth/authorize
          scopes:
            read: Grants read access
            write: Grants write access
    bearerAuth:
      type: http
      scheme: bearer
security:
  - basicAuth: []
  - apiKeyAuth: []
  - oauth2Implicit:
      - read
  - bearerAuth: []
paths:
  /users:
    get:
      summary: List all users
      security:
        - basicAuth: []
        - apiKeyAuth: []
        - oauth2Implicit:
            - read
        - bearerAuth: []
      responses:
        '200':
          description: A list of users